version: '3.8'

services:

  notify-service-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./infra/nginx/configs:/etc/nginx/conf.d:rw

  notify-service-postgres:
    image: postgres:13
    container_name: notify-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data


  notify-service-api:
    ports:
      - ${BACKEND_PORT:-8001}:8001
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    depends_on:
      - notify-service-postgres
    volumes:
      - ./src/app:/opt/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload

volumes:
  db_data
