version: '3.8'

services:

  notify-service-nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    container_name: notify-service-nginx
    restart: unless-stopped
    networks:
      - notify-service-network
    depends_on:
      - notify-service-api

  notify-service-postgres:
    image: postgres:13
    container_name: notify-service-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - notify-service-network
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data

  notify-service-api:
    container_name: notify-service-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    networks:
      - notify-service-network
    env_file:
      - ./src/.env

networks:
  notify-service-network:
    name: notify-service-network
    external: true

volumes:
  db_data:
