version: '3.8'

services:

  notify-service-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./infra/nginx/configs:/etc/nginx/conf.d:rw

  notify-service-postgres:
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  notify-service-api:
    ports:
      - ${BACKEND_PORT:-8001}:8001
    volumes:
      - ./src/app:/opt/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  notify-service-migration:
    volumes:
      - ./src:/opt/app
    # command: sleep 1
