version: '3.8'

services:

  notify-service-nginx:
    ports:
      - ${FRONTEND_PORT:-80}:80

  notify-service-api:
    expose:
      - 8001
    command: poetry run gunicorn -c gunicorn.conf.py main:app
