[tool.poetry]
name = "notify-service"
version = "0.1.0"
description = "Notify Service"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "notify_service"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.103.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
