"""add template type

Revision ID: 0ebd66ec9c87
Revises: 77bc96ecfcaa
Create Date: 2023-09-04 17:39:28.072735

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ebd66ec9c87'
down_revision: Union[str, None] = '77bc96ecfcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('notifications_template_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(
        None,
        'notifications',
        'templates',
        ['template_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.drop_constraint('schedule_notification_id_fkey', 'schedule', type_='foreignkey')
    op.create_foreign_key(
        None,
        'schedule',
        'notifications',
        ['notification_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.drop_constraint('templates_sender_id_fkey', 'templates', type_='foreignkey')
    op.drop_constraint('templates_wrapper_id_fkey', 'templates', type_='foreignkey')
    op.create_foreign_key(
        None,
        'templates',
        'senders',
        ['sender_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        None,
        'templates',
        'wrappers',
        ['wrapper_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'templates', schema='public', type_='foreignkey')
    op.create_foreign_key(
        'templates_wrapper_id_fkey',
        'templates',
        'wrappers',
        ['wrapper_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.create_foreign_key(
        'templates_sender_id_fkey',
        'templates',
        'senders',
        ['sender_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.drop_constraint(None, 'schedule', schema='public', type_='foreignkey')
    op.create_foreign_key(
        'schedule_notification_id_fkey',
        'schedule',
        'notifications',
        ['notification_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    op.drop_constraint(None, 'notifications', schema='public', type_='foreignkey')
    op.create_foreign_key(
        'notifications_template_id_fkey',
        'notifications',
        'templates',
        ['template_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###
